<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-GGLBD97Q" failures="2" tests="6" name="Test" time="69.719" errors="0" timestamp="2021-11-27T21:54:18 IST">
  <testcase classname="com.application.test.ApplicationTest" name="VerifyApplicationTitle" time="4.067"/>
  <testcase classname="com.application.test.ApplicationTest" name="VerifyApplicationLogin" time="8.701"/>
  <testcase classname="com.application.test.ApplicationTest" name="VerifyApplicationLogin" time="15.148">
    <failure type="java.lang.AssertionError" message="Login Process is Not Successful">
      <![CDATA[java.lang.AssertionError: Login Process is Not Successful
at com.application.pages.LoginPage.verifyApplicationLogin(LoginPage.java:91)
at com.application.test.ApplicationTest.VerifyApplicationLogin(ApplicationTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- VerifyApplicationLogin -->
  <testcase classname="com.application.test.ApplicationTest" name="VerifyApplicationLogin" time="15.374">
    <failure type="java.lang.AssertionError" message="Login Process is Not Successful">
      <![CDATA[java.lang.AssertionError: Login Process is Not Successful
at com.application.pages.LoginPage.verifyApplicationLogin(LoginPage.java:91)
at com.application.test.ApplicationTest.VerifyApplicationLogin(ApplicationTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- VerifyApplicationLogin -->
  <testcase classname="com.application.test.ApplicationTest" name="VerifyApplicationLogout" time="9.236"/>
  <testcase classname="com.application.test.ApplicationTest" name="VerifyForgotPasswordFeature" time="5.253"/>
</testsuite> <!-- Test -->
